# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pipeline_server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pipeline_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pipeline_server.proto\"l\n\x15ProcessedFrameRequest\x12\x12\n\nvideo_name\x18\x01 \x01(\t\x12\x12\n\nframe_name\x18\x02 \x01(\t\x12\x12\n\nframe_data\x18\x03 \x01(\x0c\x12\x17\n\x0f\x61nnotation_json\x18\x04 \x01(\t\"!\n\x0eUploadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0c\x42\x61tchRequest\x12\x12\n\nbatch_size\x18\x01 \x01(\x05\"5\n\x0eProcessedBatch\x12\x0e\n\x06\x66rames\x18\x01 \x03(\x0c\x12\x13\n\x0b\x61nnotations\x18\x02 \x03(\t2\x8c\x01\n\x0ePipelineServer\x12>\n\x11SendProcessedData\x12\x16.ProcessedFrameRequest\x1a\x0f.UploadResponse(\x01\x12:\n\x16StreamProcessedBatches\x12\r.BatchRequest\x1a\x0f.ProcessedBatch0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipeline_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSEDFRAMEREQUEST']._serialized_start=25
  _globals['_PROCESSEDFRAMEREQUEST']._serialized_end=133
  _globals['_UPLOADRESPONSE']._serialized_start=135
  _globals['_UPLOADRESPONSE']._serialized_end=168
  _globals['_BATCHREQUEST']._serialized_start=170
  _globals['_BATCHREQUEST']._serialized_end=204
  _globals['_PROCESSEDBATCH']._serialized_start=206
  _globals['_PROCESSEDBATCH']._serialized_end=259
  _globals['_PIPELINESERVER']._serialized_start=262
  _globals['_PIPELINESERVER']._serialized_end=402
# @@protoc_insertion_point(module_scope)
