# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pipeline_server_pb2 as pipeline__server__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pipeline_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PipelineServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendProcessedData = channel.stream_unary(
                '/PipelineServer/SendProcessedData',
                request_serializer=pipeline__server__pb2.ProcessedFrameRequest.SerializeToString,
                response_deserializer=pipeline__server__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.StreamProcessedBatches = channel.unary_stream(
                '/PipelineServer/StreamProcessedBatches',
                request_serializer=pipeline__server__pb2.BatchRequest.SerializeToString,
                response_deserializer=pipeline__server__pb2.ProcessedBatch.FromString,
                _registered_method=True)


class PipelineServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendProcessedData(self, request_iterator, context):
        """Pipeline sends processed frames + annotations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamProcessedBatches(self, request, context):
        """Training machines request processed batches
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipelineServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendProcessedData': grpc.stream_unary_rpc_method_handler(
                    servicer.SendProcessedData,
                    request_deserializer=pipeline__server__pb2.ProcessedFrameRequest.FromString,
                    response_serializer=pipeline__server__pb2.UploadResponse.SerializeToString,
            ),
            'StreamProcessedBatches': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamProcessedBatches,
                    request_deserializer=pipeline__server__pb2.BatchRequest.FromString,
                    response_serializer=pipeline__server__pb2.ProcessedBatch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PipelineServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PipelineServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PipelineServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendProcessedData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/PipelineServer/SendProcessedData',
            pipeline__server__pb2.ProcessedFrameRequest.SerializeToString,
            pipeline__server__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamProcessedBatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/PipelineServer/StreamProcessedBatches',
            pipeline__server__pb2.BatchRequest.SerializeToString,
            pipeline__server__pb2.ProcessedBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
